---
- hosts: webservers
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.key }}"
        comment: "{{ item.key }}@example.com"
        home: "/home/{{ item.key }}"
        password: "{{ item.value | password_hash('sha512') }}"
        update_password: on_create
      no_log: True       
      loop:
        "{{ users | dict2items }}"
...